name: LuCI i18n CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天检查一次上游更新

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext
        pip install polib

    - name: Sync from upstream (example)
      run: |
        # 这里添加从上游仓库同步.po文件的逻辑
        # 例如使用git或curl获取最新英文版文件
        echo "TODO: Add actual sync logic"

    - name: Validate PO files
      run: |
        for po_file in $(find . -name "*.po"); do
          msgfmt --check-format --check-header $po_file -o /dev/null
        done

    - name: Build LMO files
      run: |
        for po_file in $(find . -name "*.po"); do
          lmo_file="${po_file%.po}.lmo"
          msgfmt $po_file -o $lmo_file
        done

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto update translations"
        git push
