name: LuCI i18n CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每日自动检查上游更新

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext make

      - name: Validate .po files
        run: |
          for po_file in $(find . -name "*.po"); do
            msgfmt --check-format --check-header $po_file -o /dev/null || exit 1
          done

      - name: Build .lmo files
        run: |
          mkdir -p build
          for po_file in $(find . -name "*.po"); do
            lmo_file="build/$(basename ${po_file%.po}).lmo"
            msgfmt $po_file -o $lmo_file
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xray-zh-cn-translations
          path: build/*.lmo
          if-no-files-found: error

      - name: Auto-commit (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-build translations" || echo "No changes to commit"
          git push
