name: Build LuCI Translations

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y gettext make

      - name: Validate .po files
        run: make check

      - name: Build .lmo files
        run: make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # 必须使用 v4
        with:
          name: translations
          path: |
            ./**/*.lmo    # 明确指定路径
            ./**/*.po
          if-no-files-found: error  # 如果无文件则报错

      - name: Clean
        run: make clean
