name: Build LuCI Translations

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y gettext make

      - name: Validate .po files
        run: make check  # 如果失败，Action 会自动终止

      - name: Build .lmo files
        run: make all    # 编译核心步骤

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-translations
          path: |
            **/*.lmo
            **/*.po

      - name: Clean (optional)
        if: always()    # 无论成功失败都执行清理
        run: make clean
